apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: cs361-ingestion:local
          ports:
            - containerPort: 8081
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/094728020196/cs361-telemetry-queue"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-svc
spec:
  selector:
    app: ingestion
  ports:
    - port: 8081
      targetPort: 8081
