apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: cs361-worker:20260219160209
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/094728020196/cs361-telemetry-queue"
            - name: DDB_TABLE
              value: "Telemetry"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_SECRET_ACCESS_KEY


